### PR TITLE
TypeScript support (definition files) + a few small enhancement proposals

### PR DESCRIPTION
**Pull request by tchakabam**
This patch contains:

- TypeScript `.d.ts` files in order to import the lib in TS
- Example/Check for usage from `tsc` or `ts-node`

Optionally: 

- Add `"use strict";` on all examples
- Fix in example to declare `fhandle` var (would otherwise crash in strict mode)
- (Important?) fix in NAPI callback `NodeSRT:GetSockOpt` to propagate errors into JS runtime (trigger throw before return from func)
- Misc small fixes and code quality improvements
- Improve `package.json` metadata (will allow better keyword searchability on NPM registry)
- Add `.editorconfig` for editing with correct indentation and fix whitespace noise
- Add `eslint` to enable static code checks and fix potential issues upfront
- Replace magic numbers in `SRTReadStream` impl by constants at top of module scope

### CODE REVIEW

**Comment by tchakabam** [comment]
Please note that all the other proposals are optional improvements to this JS package from my experience, but not necessary for the core concern here which was to add type declaration files in order to use these bindings also TypeScript bindings :)

**Comment by birme** [comment]
Thanks! Will have a look as soon as I am back home

**Comment by tchakabam** [comment]
Thank you! No rush for us to get this merged in any way :) Just wanted to make sure this became visible for you ;)

The branch here is a mix of TypeScript support + one fix I consider critical + a lot of stuff that isn't, but rather "optional" :) 

So I made sure commits are self-contained. We can always cherry-pick single commits from and split it up into several tickets here if you prefer.

**Comment by birme** [comment]
I had a brief look at they all made sense to me. Will approve and merge during the weekend. Many thanks for the contribution!

**Review by birme — APPROVED** [review]

**Pull request merged**
